[build]
  command = "npm run build:skip-ts"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 禁用Cypress插件
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs]
    enable = false
