// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 使用环境变量或回退到硬编码值（仅用于开发）
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://eyfkefeyhsrmutvezwxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5ZmtlZmV5aHNybXV0dmV6d3hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MDQyMDksImV4cCI6MjA1NTQ4MDIwOX0.RhZ4OoAwGQE6Gvm4UuNvB9W7kWS0rmxGIilEOxI2wSM";

// 调试信息
console.log('Supabase Client Initialization:');
console.log('SUPABASE_URL:', SUPABASE_URL);
console.log('SUPABASE_PUBLISHABLE_KEY length:', SUPABASE_PUBLISHABLE_KEY?.length);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// 创建客户端，并确保每个请求都包含正确的头信息
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true
  },
  global: {
    headers: {
      'apikey': SUPABASE_PUBLISHABLE_KEY
    }
  }
});